image: proboci/ubuntu-16.04-lamp:php7.2-nightly
steps:
  - name: Probo LAMPApp configuration for Concrete5.
    plugin: LAMPApp
    databaseName: concrete5demo
    databaseUser: root
    mysqlCnfOptions:
      key_buffer_size: 36M
      max_allowed_packet: 36M
    phpIniOptions:
      upload_max_filesize: 25M
      post_max_size: 25M
      memory_limit: 256M
  - plugin: Script
    name: Install Concrete 5 site. 
    script: |
      mkdir $SRC_DIR/application/config $SRC_DIR/packages $SRC_DIR/application/packages
      chmod -R 775 .
      chown -R www-data:www-data .
      $SRC_DIR/concrete/bin/concrete5 c5:install --db-server=localhost --db-username=root --db-password=strongpassword --db-database=concrete5demo --site=Test --admin-email=jmoore@zivtech.com --admin-password=PASSWORD --starting-point=elemental_full
      chown -Rf www-data:www-data .
      chmod -Rf 775 .
